# Generated by Django 4.1 on 2023-04-10 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
