# Generated by Django 4.2 on 2023-04-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeApp", "0002_alter_employee_hire_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="name",
            new_name="depart_name",
        ),
    ]
