# Generated by Django 4.2 on 2023-04-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeApp", "0003_rename_name_department_depart_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="depart_name",
            new_name="name",
        ),
    ]
